version: "3.7"

services:

  pizzeria-db:
    container_name: pizzeria-db
    image: mysql:latest
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql/data
      - ./services/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - services/mysql/.env
    ports:
      - "5432:5432"