version: "3.7"

services:

  pizzeria-db:
    container_name: pizzeria-db
    image: mysql:latest
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - services/mysql/.env
    ports:
      - "3307:3306"